ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [com.muff.ApplicationKt.module]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/muff"
    url = ${?DATABASE_URL}
    user = "muff"
    user = ${?DATABASE_USER}
    password = "muff"
    password = ${?DATABASE_PASSWORD}
    maxPoolSize = 10
    maxPoolSize = ${?DATABASE_MAX_POOL_SIZE}
}

jobs {
    rssPollingIntervalMinutes = 10
    rssPollingIntervalMinutes = ${?RSS_POLLING_INTERVAL_MINUTES}
    popularityAggregationIntervalMinutes = 30
    popularityAggregationIntervalMinutes = ${?POPULARITY_AGGREGATION_INTERVAL_MINUTES}
}
